<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZb02HAN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZb02HAN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZb02HAN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZb02HAN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZb02HAN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zb02HAN',
    'container.build_id' => '2d6f5057',
    'container.build_time' => 1743090590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZb02HAN');
